@startuml seq_registerEmployee
hide footbox
actor "Guest" as guest
participant "AppController" as app
participant "Employees" as em
participant "Employee" as inst

activate guest
activate app
guest -> app: registerEmployee(givenName, surName, initials)

alt givenName.isEmpty() or surName.isEmpty()

app --> guest: "For- /efternavn mangler"

else 
alt initials.isEmpty()
app --> guest: "Initialer mangler"

else

loop for each Employee \n in Employees
app -> em: employeeExists(initials)
activate em
end
alt employeeExists(initials) == true
em --> app: true
app --> guest: "Medarbejder med initialer {initials} eksisterer allerede"
else
em --> app: false
deactivate em
app -> inst **: newEmployee(givenName, surName, initials)
activate inst
inst --> app: e: Employee
deactivate inst
app -> em: add(e)
activate em
em --> app
deactivate em
app --> guest: "Employee added"
deactivate app
end
end
end
@enduml