@startuml createActivityNoPLCase1
actor "Employee" as emp
participant AppController as app
participant Project as p
participant ProjectActivity as ppa

activate emp
emp -> app : createProjectActivity(23001)
activate app
app -> p : createActivity("Graphics design")
activate p
alt No activity with title "Graphics design" is present
p -> ppa : <<create>>
activate ppa
ppa --> p : ProjectActivity("Graphics design")
deactivate ppa
deactivate p
else An activity with title "Graphics design" is present
p --> app : "Projektaktivitet findes allerede"
activate p
deactivate p
app --> emp : "Projektaktivitet findes allerede"
end
@enduml