@startuml
actor "Employee" as e
participant "MainController" as app
participant "Date server" as ds
participant "Project manager" as pm

e -> app : createProject(title)
activate app

app -> app : isLoggedIn()
app --> e : Kun medarbejdere kan oprette et projekt

app -> ds : getDate
activate ds
return date 

app -> pm : createProject(title,date)
activate pm 

pm -> pm : validTitle()
pm --> e : En projekttitel mangler

return project

return project

@enduml