@startuml
actor "Employee" as e
participant "MainController" as app
participant "Date server" as ds
participant "Project manager" as pm
participant "Project" as p

e -> app : editProject(project,property,value)
activate app


app -> pm : editProject(employee,project,property,value)
activate pm 

pm -> pm : editAllowed(employee,project,property)
pm --> e : Du har ikke rettigheder til dette

pm -> p : edit(property,value)
activate p 
return true

return true

return true


@enduml