@startuml seqAssignEmployee
autonumber
hide footbox
skinparam style strictuml
hide unlinked
actor "Employee" as pl
participant "TaskFusion" as app << (C,#ADD1B2) >>
participant "EmployeeFacade" as empfacade << (C,#ADD1B2) >>
participant "ProjectFacade" as projfacade << (C,#ADD1B2) >>
participant "ProjectRepository" as projrepo << (C,#ADD1B2) >>
participant "Project" as project << (C,#ADD1B2) >>
collections "Map<String, Project> projects" as projects << (M,Crimson) >>
participant "EmployeeRepository" as emprepo << (C,#ADD1B2) >>
pl -> app++: Assign Employee(initials)
app -> empfacade++: findByInitials(initials)
empfacade --> app--: Employee
app -> projfacade--++: assignEmployeeToProject(projectNumber, initials)
projfacade -> projrepo--++: findByProjectNumber(projectNumber)
projrepo -> projects++: get(projectNumber)
projects --> projrepo--: Project
projrepo --> projfacade--++: Project
projfacade -> app++: getLoggedInUser
app --> projfacade--: Employee
projfacade -> project --++: assignEmployee(initials, Employee)
project -> project: allowAssignEmployeeToProject
alt projectLeader != null OR loggedInUser != projectLeader
    project --> app++: OperationNotAllowedException
    app --> pl--: "Kun projektleder kan tildele medarbejdere til projektet"
else
    project -> emprepo++: findByInitials(initials)
    emprepo --> project--: Employee
    project -> project: assignedEmployees.put(initials, Employee)
    project --> app--++
    app --> pl--: "Tilføjet til projekt"
end
@enduml