@startuml seqLogin
autonumber
hide footbox
skinparam style strictuml
hide unlinked
actor "Employee" as emp
participant "TaskFusion" as app << (C,#ADD1B2) >>
participant "EmployeeFacade" as empfacade << (C,#ADD1B2) >>
participant "EmployeeRepository" as emprepo << (C,#ADD1B2) >>
collections "Map<String, Employee> employees" as emps << (M,Crimson) >>
participant "Employee" as empl << (C,#ADD1B2) >>
participant "EmployeeViewModel" as empvm << (C,#ADD1B2) >>
emp -> app++: Login
app --> emp++: Prompt: Initials
emp -> app--: login(initials)
app -> empfacade--++: findEmployeeByInitials(initials)
empfacade -> emprepo--++: findByInitials(initials)
emprepo -> emps--++: get(initials)
alt Employee == null
    emps --> app++: NotFoundException
    app --> emp--: "Ukendt medarbejder"
else
    emps --> emprepo--++: Employee
    emprepo --> empfacade--++: Employee
    empfacade -> empl++: Employee.toViewModel
    empl -> empvm**: <<create>> toViewModel(this)
    empl --> empfacade--: EmployeeViewModel
    empfacade --> app--++: EmployeeViewModel
    app -> app: loggedInUser = EmployeeViewModel
    app --> emp--: "Login successful"
end
@enduml