@startuml seqRegisterEmployee
autonumber
hide footbox
skinparam style strictuml
hide unlinked
actor "Guest" as guest
participant "TaskFusion" as app << (C,#ADD1B2) >>
participant "EmployeeFacade" as empfacade << (C,#ADD1B2) >>
participant "EmployeeRepository" as emprepo << (C,#ADD1B2) >>
participant "Employee" as emp << (C,#ADD1B2) >>
collections "Map<String, Employee> employees" as emps << (M,Crimson) >>

guest -> app++: Register Employee
app --> guest++: Prompt: Firstname\nLastname
guest -> app--: firstName, lastName
app -> empfacade--++: registerEmployee(firstName,\nlastName)
empfacade -> emprepo--++: create(firstName,\nlastName)
emprepo -> emp**: <<create>>
deactivate emprepo
emp -> emp++: createInitials()
loop for int : lastName.length()
    emp --> emprepo--++: initialsExist(initials)
    emprepo -> emprepo: findByInitials(initials)
    emprepo -> emps++: get(initials)
    emps --> emprepo--: Employee
end
alt !Employee == null
    emprepo -> emp++: true
    emp --> app--++: ExhaustedOptionsException
    app --> guest--: "Kunne ikke generere\nunikke initialer"
else Employee == null
    emprepo -> emp++: false
    emp -> emp: this = initials
    emp --> emprepo--: Employee,\ninitials
    emprepo -> emps++: put(initials, Employee)
    deactivate emps
    emprepo --> empfacade--++: Employee
    empfacade --> app --++
    app --> guest--: "Employee created"
end
@enduml