@startuml createActivityNoPLCase3
actor "Employee" as emp
participant AppController as app
participant Project as p

activate emp

activate app
emp -> app : editProject(23001)
app -> p : setStartWeek("Graphics design", 2304)
activate p
alt 2304 <= endWeek
p -> p : activity = this.activities.find("Graphics design")
p -> p : activity.setStartWeek(2304)
else 2304 > endWeek
deactivate p
p --> app : "Starttid skal være før eller ens med sluttid"
activate p
app --> emp : "Starttid skal være før eller ens med sluttid"
deactivate p
end
@enduml