@startuml Login
' skinparam ParticipantPadding 50
actor "Guest" as guest
participant "AppController" as app
participant "Employees" as em

activate guest
guest -> app : login(initials)
activate app
loop for each Employee \n in Employees
app -> em: employeeExists(initials)
activate em
end
alt employeeExists == \n false
em --> app : False
app --> guest : "Ukendt medarbejder"
else
em --> app : e : Employee
deactivate em
app -> app : : setUser(e)
app --> guest : "Logget ind som {initials}"
deactivate app
end
@enduml