@startuml createActivityNoPLGuest
actor "Guest" as g
participant AppController as app
activate g
activate app
g -> app : createProjectActivity(23001, "Graphics design")
app -> app : isLoggedIn()
alt isLoggedIn == False
app --> g : "Login krævet"
deactivate app
end
@enduml