@startuml createActivityNoPLCase4
actor "Employee" as emp
participant AppController as app
participant Project as p

activate emp
activate app
emp -> app : editProject(23001)
app -> p : setEndWeek("Graphics design", 2303)
activate p
alt 2303 >= startWeek
p -> p : pa : activites.get("Graphics design")
p -> p : pa.setStartWeek(2303)
p --> emp : "Graphics design startweek set to 2303"
else 2303 < startWeek
deactivate p
p --> app : "Sluttid skal være efter eller ens med starttid"
activate p
app --> emp : "Sluttid skal være efter eller ens med starttid"
deactivate p
end
@enduml