@startuml Logout
hide footbox
actor "Employee" as em
participant "AppController" as app

activate em
em -> app : logout()
activate app
app -> app : setUser(NULL)
app --> em : "Logget ud"
deactivate app
@enduml