@startuml BecomeProjectLeader
hide footbox
actor "Employee" as e
participant "AppController" as app
participant "Project" as p

activate e
e -> app : assignSelfProjectLeader(e: Employee, p1: project)
activate app
alt p1 is not in the collection of project
app --> e : "Projektet kunne ikke findes i samlingen af projekter"
else
app -> p : projectLeaderExists()
activate p
alt A project leader is already assigned
p --> app : true
app --> e : "Der er allerede en projektleder på dette projekt"
else
p -> app : false
app -> p : assignProjectLeader(e)
p -> p : projectLeader = e
p --> app
app --> e : "Du er nu projektleder på {p1}"
deactivate p
deactivate app
end
end