@startuml createActivityPL
actor "Employee" as emp
participant AppController as app
participant Project as p
participant ProjectActivity as pa

activate emp
emp -> app : createProjectActivity(23001)
activate app
activate p
app -> p : getProjectLeader()
p --> app : pl : String
deactivate p
app -> app : checkEmployee(initials, pl)
alt The employee is the project leader
activate p
app -> p : createActivity("Graphics design")
p -> pa** : <<create>>
activate pa
pa --> p : pa : ProjectActivity
deactivate pa
p -> p : activities.add("Graphics design", pa)
deactivate p
else The employee is not the project leader
app --> emp : "Kun projektlederen kan redigere denne projektaktivitet"
deactivate app
end
@enduml