@startuml createActivityNoPLCase3
hide footbox
actor "Employee" as emp
participant AppController as app
participant Project as p

activate emp

activate app
emp -> app : editProject(23001)
app -> p : setStartWeek("Graphics design", 2304)
activate p
alt 2304 <= endWeek
p -> p : pa : activites.get("Graphics design")
p -> p : pa.setStartWeek(2304)
p --> emp : "Graphics design endweek set to 2304"
else 2304 > endWeek
deactivate p
p --> app : "Starttid skal være før eller ens med sluttid"
activate p
app --> emp : "Starttid skal være før eller ens med sluttid"
deactivate p
end


hide footbox
@enduml