@startuml seqViewWorktime
autonumber
hide footbox
skinparam style strictuml
hide unlinked
actor "Employee" as employee
participant "TaskFusion" as app << (C,#ADD1B2) >>
participant "ProjectFacade" as projectfacade << (C,#ADD1B2) >>
participant "ProjectRepository" as projectrepo << (C,#ADD1B2) >>
participant "Project" as project << (C,#ADD1B2) >>
participant "ProjectActivity" as projectactivity << (C,#ADD1B2) >>
collections "List<Registration> worktimes" as wts << (L, DarkCyan) >>
participant "WorktimeRegistration" as wt << (C,#ADD1B2) >>
collections "List<Registration> userWorktimes" as empwts << (L, DarkCyan) >>
employee -> app++: View\nworktime\nregistrations
app -> projectfacade--++: getUserWorktime\nRegistrations(\nactivityTitle,\nprojectNumber)
projectfacade -> projectfacade: requireLogin()
projectfacade -> app--++: isLoggedIn()
alt loggedInUser == null
    app -> projectfacade++: false
    projectfacade --> app--: OperationNotAllowed\nException
    app --> employee: "Login krævet"
else
    app -> projectfacade--++: true
    projectfacade -> projectrepo++: findByProjectNumber(\nprojectNumber)
    projectrepo --> projectfacade--: Project
    projectfacade -> project++: findProjectActivity(activityTitle)
    project --> projectfacade--: ProjectActivity
    projectfacade -> projectactivity--++: getWorktimeRegistrationsForEmployee(initials)
    projectactivity -> empwts**: <<create>>
    loop registration in worktimes
        projectactivity -> wts++: getInitials()
        wts -> wt++: getInitials()
        wt --> wts--: initials
        wts --> projectactivity--: initials
        alt if initials == loggedInUserInitials
            projectactivity -> empwts++: add(registration)
            deactivate empwts
        end
    end
    projectactivity --> projectfacade--++: List userWorkTimes
    projectfacade --> app--++: List userWorkTimes
    app --> employee --: List of\nworktime\nregistrations
end

@enduml