@startuml ClassDiagram_simple
skinparam linetype ortho
skinparam Nodesep 200
skinparam Ranksep 150


package "Facade-layer" as FacadeLayer {

    class TaskFusion {
        --
    }

    interface AuthentificationFacadeInterface {
    }

    interface EmployeeFacadeInterface {

    }

    interface RegularActivityFacadeInterface {
    }

    class EmployeeFacade {
    }

    EmployeeFacade .u.|> EmployeeFacadeInterface
    EmployeeFacade .u.|> RegularActivityFacadeInterface
    TaskFusion -->"1" EmployeeFacadeInterface
    TaskFusion -->"1" RegularActivityFacadeInterface
    TaskFusion -->"1" AuthentificationFacadeInterface


    interface ProjectFacadeInterface{

    }

    interface ReportFacadeInterface {

    }

    interface ProjectActivityFacadeInterface {

    }


    class ProjectFacade {
    }

    ProjectFacade .u.|> ProjectFacadeInterface
    ProjectFacade .u.|> ProjectActivityFacadeInterface
    ProjectFacade .u.|> ReportFacadeInterface
    TaskFusion -->"1" ProjectFacadeInterface
    TaskFusion -->"1" ProjectActivityFacadeInterface
    TaskFusion -->"1" ReportFacadeInterface
}


package "Persistency-layer" as PersistencyLayer {
    class ProjectRepository << (S,#FF7700) Singleton >>{
    }

    class EmployeeRepository << (S,#FF7700) Singleton >>{
    }

}


package "Domain-layer" as DomainLayer {

    interface ConvertibleToViewModel{
        + toViewModel() : ViewModel
    }

    class Report {
        - title : String 
        - projectNumber : String 
        - customer : String 
        - reportDate : Calendar       
    }

    class Project{
        projectTitle : String 
        projectNumber : String
        customer : String
    }

    class ProjectActivity{
    }

    class ActivityWithWorktimeRegistrations <<(A, orchid)abstract>> {
        timeBudget : int
    }

    class Activity <<(A, orchid)abstract>>{
        title : String
        startWeek : int
        endWeek : int
    }

    class RegularActivity{
        id : int
    }

    class Employee{
        initials : String
        firstName : String
        lastName : String
    }

    class WorktimeRegistration {
        id : int
        initials : String
        time : double
        date : Calendar
    }

}

PersistencyLayer -d[hidden]-> DomainLayer


ProjectFacade --> "1" ProjectRepository : projectRepository
EmployeeFacade --> "1" EmployeeRepository : employeeRepository

ProjectRepository --> "0..*" Project : projects
Project --> "0..*" Report : reports

EmployeeRepository --> "0..*" Employee : employees

Activity <|-- ActivityWithWorktimeRegistrations
ActivityWithWorktimeRegistrations <|-- ProjectActivity
Activity <|-- RegularActivity
ActivityWithWorktimeRegistrations -->"0..*" WorktimeRegistration : worktimeRegistrations

Project --> "1" Employee : projectLeader
Project --> "0..*" Employee : employees
Employee --> "0..*" Project : projects
Project -> "0..*" ProjectActivity : activities
Employee -> "0..*" RegularActivity : regularActivities

Report --> "1" Employee : projectLeader
Report --> "0..*" Employee : employees
Report --> "0..*" ProjectActivity : activities


'Employee --> "0..*" WorktimeRegistrations : worktimeRegistrations
Project ..|> ConvertibleToViewModel
Employee ..|> ConvertibleToViewModel
ProjectActivity ..|> ConvertibleToViewModel
RegularActivity ..|> ConvertibleToViewModel
WorktimeRegistration ..|> ConvertibleToViewModel
Report ..|> ConvertibleToViewModel

@enduml