@startuml 

[TaskFusion facade] as tfFacade
[TaskFusion CLI] as tfCLI

tfFacade - tfCLI

[GuestMenuController] as GMC 

tfCLI - GMC 

[LoginView] as login 
[RegisterEmployeeView] as regEmp 

GMC - login 
GMC - regEmp 

[EmployeMenuController] as EMC

login - EMC

[listProjectsView] as listProj
[createProjectView] as createProj
[listRegularActivitiesView] as listRegAct
[createRegularActivitiesView] as createRegAct

EMC - listProj
EMC - createProj
EMC - listRegAct
EMC - createRegAct

@enduml