@startuml 

left to right direction

actor "Medarbejder" as worker

package "Projektstyring" {
    usecase "Opret projekt" as create_project
    usecase "Opret aktivitet til projekt" as create_project_activity
    usecase "Tilknyt medarbejder til projekt" as assign_project_user
    usecase "Tilknyt projektleder til projekt" as assign_project_leader
}

guest --> create_project
guest --> create_project_activity
guest --> assign_project_user
guest --> assign_project_leader



@enduml