@startuml 

left to right direction

actor "Gæst" as guest

package "Projektstyring & tidsregistrering" {

    package "Projektstyring" {
        usecase "Opret projekt" as create_project
    }
    
    package "Brugeradministration" {
        usecase "Opret medarbejder" as create_worker
        usecase "Tilknyt medarbejder til projekt" as assign_project_user
        usecase "Tilknyt projektleder til projekt" as assign_project_leader
    }

    package "Aktivitetshåndtering" {
        usecase "Opret aktivitet til projekter" as create_project_activity
    }
    
}

guest --> create_project
guest --> create_project_activity
guest --> assign_project_user
guest --> assign_project_leader
guest --> create_worker

@enduml