@startuml ClassDiagram
skinparam linetype ortho
skinparam Nodesep 200
' skinparam Ranksep 50
class AppController{
    login(Emplyee e)
    logout()
    isLoggedIn()
    employeeExist()
    newEmployee()
    setUser(Employee e)
    getProjectLeader(Project p)
    checkEmployee(Employee e)
    editProject(Project p, Object property, Object value)
}
class Report{
    remainingWorkHours : int
    incompleteActivities : List
}
class Project{
    projectNumber : int
    customer : String
    internal : boolean
    startWeek : int
    endWeek : int
    createActivity(String)
    setTimeBudget(String, int)
    setStartWeek(String, int)
    setEndWeek(String, int)
    editProject(Oject property, Object value)
}
class ProjectActivity{
    worktimeRegistrations : List
    timeBudget : int
    setTimeBudget(int)
}
class Activity <<(A, orchid)abstract>>{
    title : String
    startWeek : int
    endWeek : int
    setEndWeek(String, int)
    setStartWeek(String, int)
}
class RegularActivity{
}
class Employee{
    initials : String
    givenName : String
    surName : String
}
Activity <|-u- ProjectActivity
Activity <|- RegularActivity
AppController -r-> "0..*" Project : projects
AppController -> Report : generateReport(Project project)
Project -[hidden]u-> Report
AppController -d-> "0..*" Employee : employees
Project -u-> "1" Report : project
Project -d-> "1    " Employee : projectLeader
Project -d-> "0..*" Employee : employees
Project -> "0..*" ProjectActivity : activities
Employee -> "0..*" RegularActivity : regularActivities
@enduml