@startuml usecases
left to right direction
actor Guest as guest
actor Employee as emp
actor "Project Leader" as pl

rectangle TaskFusion{
usecase "Set time budget for activity" as timebudget
usecase "Generate report for project" as generatereport
usecase "Login" as login
usecase "Logout" as logout
usecase "Register employee" as registeremp
usecase "Create project" as createproj
usecase "Create regular activity" as createregact
usecase "Create project activity" as createrprojact
usecase "Register work time" as regwt
usecase "Take project leader role" as plrole
usecase "Assign employees to project" as assignemplpro
}

createrprojact -[hidden]l- assignemplpro
createrprojact -[hidden]l- login
login -[hidden]l- logout
logout -[hidden]l- plrole
plrole -[hidden]l- createregact
createregact -[hidden]l- createproj
createproj -[hidden]l- regwt
login -[hidden]d- generatereport
logout -[hidden]d- timebudget
plrole -[hidden]d- registeremp
assignemplpro -[hidden]r- generatereport
generatereport -[hidden]l- timebudget

emp --> login
emp --> logout
emp --> createproj
emp --> createregact
emp --> createrprojact: If no project leader\nis assigned
emp --> assignemplpro
emp --> regwt
emp --> plrole
pl -up-> timebudget
pl -up-> generatereport
pl -up-> assignemplpro
pl -up-> createrprojact
guest -up-> registeremp

@enduml