@startuml usecasesEmployee
left to right direction
actor Employee as emp

rectangle TaskFusion{
usecase "Set time budget for activity" as timebudget
usecase "Login" as login
usecase "Logout" as logout
usecase "Create project" as createproj
usecase "Create regular activity" as createregact
usecase "Create project activity" as createrprojact
usecase "Register work time" as regwt
usecase "Take project leader role" as plrole
usecase "Assign employees to project" as assignemplpro
usecase "View regular activity" as viewregact
usecase "View wortime registrations on project activity" as viewprojact
usecase "View employees assigned to project" as viewemployees
}

emp --> login
emp --> logout
emp --> createproj
emp --> createregact
emp --> createrprojact: If no project leader\nis assigned
emp --> assignemplpro: If no project leader\nis assigned
emp --> timebudget: If no project leader\nis assigned
emp --> regwt
emp --> plrole
emp --> viewregact
emp --> viewprojact
emp --> viewemployees

@enduml