@startuml ClassDiagram
skinparam linetype ortho
skinparam Nodesep 150
skinparam Ranksep 150


    
class "TaskFusion" as app{
    - loggedInUser : Employee
    --
    + login(initials) : boolean
    + logout()
    + isLoggedIn() : boolean
}

package "Facade-layer" {

    class EmployeeFacade {
        --
        + registerEmployee(firstName, lastName)
        + findEmployee(initials)
    }

    class ProjectFacade {
        + createProject(projectTitle)
        + assignCustomerToProject(projectNumber, customer)
    }
}


package "Persistency-layer" {
    class ProjectRepository << (S,#FF7700) Singleton >>{
        --
        + findByProjectNumber(projectNumber) : Project
        + create(title) : void
    }

    class EmployeeRepository << (S,#FF7700) Singleton >>{
        --
        + findByInitials(initials) : Employee
        + create(firstName,lastName) : void
    }

}


package "Domain-layer" {

    interface ConvertibleToViewModel{
        + toViewModel() : ViewModel
    }

    class Report {
        remainingWorkHours : int
        incompleteActivities : List
        --
    }

    class Project{
        projectNumber : int
        customer : String
        internal : boolean
        startWeek : int
        endWeek : int
        --
        + createActivity(String)
        + setTimeBudget(int)
        + setStartWeek(int)
        + setEndWeek(int)
        + setProjectLeader(Employee)
    }

    class ProjectActivity{
        timeBudget : int
        --
        + setTimeBudget(int)
    }
    
    class Activity <<(A, orchid)abstract>>{
        title : String
        startWeek : int
        endWeek : int
        --
        + setEndWeek(String, int)
        + setStartWeek(String, int)
    }
    class RegularActivity{
        --
    }

    class Employee{
        - initials : String
        - firstName : String
        - lastName : String
        --
        - validateFirstName(firstName) : String
        - validateLastName(lastName) : String
        - createInitials() : void
    }

    class WorktimeRegistration {
        - initials : String 
        - time : double 
        - date : Calendar
    }

}
app --> "1" ProjectFacade : projectFacade
app --> "1" EmployeeFacade : employeeFacade

ProjectFacade --> "1" ProjectRepository : projectRepository
EmployeeFacade --> "1" EmployeeRepository : employeeRepository

ProjectRepository --> "0..*" Project : projects
Project -> Report : generateReport(Project project)

EmployeeRepository --> "0..*" Employee : employees

app --> "0..1" Employee : user

Activity <|-- ProjectActivity
Activity <|- RegularActivity

Project --> "1" Employee : projectLeader
Project --> "0..*" Employee : employees
Employee --> "0..*" Project : projects
Project -> "0..*" ProjectActivity : activities
Employee -> "0..*" RegularActivity : regularActivities

ProjectActivity --> "0..*" WorktimeRegistration : worktimeRegistrations

'Employee --> "0..*" WorktimeRegistrations : worktimeRegistrations
Project ..|> ConvertibleToViewModel
Employee ..|> ConvertibleToViewModel
ProjectActivity ..|> ConvertibleToViewModel
RegularActivity ..|> ConvertibleToViewModel
WorktimeRegistration ..|> ConvertibleToViewModel
Report ..|> ConvertibleToViewModel

@enduml