@startuml
left to right direction
(*) --> "
{{
salt
{+
title GÆST MENU 
header GuestMenuController
<&chevron-right> Login
<&chevron-right> Opret medarbejder
<&chevron-right> Luk
}
}}
" as GuestMenuController

GuestMenuController --> "
{{
salt
{+
title LOGIN
header LoginView
<&terminal> Indtast dine initialer
}
}}
" as LoginView 

LoginView --> "
{{
salt
{+
title MEDARBEJDER MENU
header EmployeeMenuController
<&chevron-right> Se projekter
<&chevron-right> Opret projekt
<color:Red><&chevron-right> Se faste aktiviteter
<color:Red><&chevron-right> Opret fast aktivitet
<&chevron-right> Logud
}
}}
" as EmployeeMenuController

GuestMenuController --> "
{{
salt
{+
title OPRET MEDARBEJDER
header RegisterEmployeeView
<&terminal> Indtast fornavn
<&terminal> Indtast efternavn
}
}}
" as RegisterEmployeeView

EmployeeMenuController --> "
{{
salt
{+
title DINE PROJEKTER
header ListProjectsView
<&menu> 23001. Kravspecifikationer
<&menu> 23002. Programdesign
<&menu> 23003. Implementering
<&menu> ...
<&terminal> Vælg projekt
}
}}
" as ListProjectsView

ListProjectsView --> "
{{
salt
{+
title PROJEKT MENU
header ProjectMenuController
Projekt nummer:    23001
Projekt leder:     kasy
Medarbejdere:      4
______________________________
<color:Red><&chevron-right> Se medarbejdere
<color:Red><&chevron-right> Tilføj medarbejder til projekt
<color:Red><&chevron-right> påtag projektleder rolle
<&chevron-right> tilbage
}
}}
" as ProjectMenuController

EmployeeMenuController --> "
{{
salt
{+
title OPRET PROJEKT
header CreateProjectView
<&terminal> Indtast projekt title
}
}}
" as CreateProjectView

EmployeeMenuController --> "
{{
salt
{+
title <color:Red>OPRET FAST AKTIVITET
header CreateRegularActivityView
<&terminal> Indtast titel
<&terminal> Indtast start uge [UUYY]
<&terminal> Indtast slut uge [UUYY]
}
}}
" as CreateRegularActivityView

EmployeeMenuController --> "
{{
salt
{+
title <color:Red>DINE FASTE AKTIVITETER
header ListRegularActivitiesView
<&menu> 1. Syg: 0423 - 0523
<&menu> 2. Ferie: 0723 - 0923
<&menu> 3. Syg: 1023 - 1023
<&menu> ...
<&terminal> Vælg aktivitet
}
}}
" as ListRegularActivitiesView

ListRegularActivitiesView --> "
{{
salt
{+
title <color:Red>FAST AKTIVITET MENU
header RegularActivityMenuController
Aktivitet titel:    Ferie
periode:  0423 - 0423
______________________________
<color:Red><&chevron-right> Ret titel
<color:Red><&chevron-right> Ret startuge
<color:Red><&chevron-right> Ret slutuge
<&chevron-right> tilbage
}
}}
" as RegularActivityMenuController

@enduml