@startuml
left to right direction
(*) --> "
{{
salt
{+
title GÆST MENU 
header GuestMenuController
<&chevron-right> Login
<&chevron-right> Opret medarbejder
<&chevron-right> Luk
}
}}
" as GuestMenuController

GuestMenuController --> "
{{
salt
{+
title LOGIN
header LoginView
<&terminal> Indtast dine initialer
}
}}
" as LoginView 

LoginView --> "
{{
salt
{+
title MEDARBEJDER MENU
header EmployeeMenuController
<&chevron-right> Se projekter
<&chevron-right> Opret projekt
<color:Red><&chevron-right> Se faste aktiviteter
<color:Red><&chevron-right> Opret fast aktivitet
<&chevron-right> Logud
}
}}
" as EmployeeMenuController

GuestMenuController --> "
{{
salt
{+
title OPRET MEDARBEJDER
header RegisterEmployeeView
<&terminal> Indtast fornavn
<&terminal> Indtast efternavn
}
}}
" as RegisterEmployeeView

EmployeeMenuController --> "
{{
salt
{+
title DINE PROJEKTER
header ListProjectsView
<&menu> 23001. Kravspecifikationer
<&menu> 23002. Programdesign
<&menu> 23003. Implementering
<&menu> ...
<&terminal> Vælg projekt
}
}}
" as ListProjectsView

ListProjectsView --> "
{{
salt
{+
title PROJEKT MENU
header ProjectMenuController
Projekt nummer:    23001
Projekt leder:     kasy
Medarbejdere:      4
<color:Red>Aktiviteter:       3
______________________________
<color:Red><&chevron-right> Se medarbejdere
<color:Red><&chevron-right> Tilføj medarbejder til projekt
<color:Red><&chevron-right> Se aktiviteter
<color:Red><&chevron-right> Tilføj aktivitet
<color:Red><&chevron-right> påtag projektleder rolle
<color:Red><&chevron-right> Generer rapport
<&chevron-right> tilbage
}
}}
" as ProjectMenuController

EmployeeMenuController --> "
{{
salt
{+
title OPRET PROJEKT
header CreateProjectView
<&terminal> Indtast projekt title
}
}}
" as CreateProjectView

EmployeeMenuController --> "
{{
salt
{+
title <color:Red>OPRET FAST AKTIVITET
header CreateRegularActivityView
<&terminal> Indtast titel
<&terminal> Indtast start uge [UUYY]
<&terminal> Indtast slut uge [UUYY]
}
}}
" as CreateRegularActivityView

EmployeeMenuController --> "
{{
salt
{+
title <color:Red>DINE FASTE AKTIVITETER
header ListRegularActivitiesView
<&menu> 1. Syg: 0423 - 0523
<&menu> 2. Ferie: 0723 - 0923
<&menu> 3. Syg: 1023 - 1023
<&menu> ...
<&terminal> Vælg aktivitet
}
}}
" as ListRegularActivitiesView

ListRegularActivitiesView --> "
{{
salt
{+
title <color:Red>FAST AKTIVITET MENU
header RegularActivityMenuController
Aktivitet titel:    Ferie
periode:  0423 - 0423
______________________________
<color:Red><&chevron-right> Ret titel
<color:Red><&chevron-right> Ret startuge
<color:Red><&chevron-right> Ret slutuge
<&chevron-right> tilbage
}
}}
" as RegularActivityMenuController

ProjectMenuController --> "
{{
salt
{+
title <color:Red>MEDARBEJDERE
header ListEmployeesView
<&menu> kasy : Kasper Sylvest
<&menu> rakr : Rasmus Kronborg
<&menu> mach : Mathies Christian
<&menu> masc : Max-Emil Scotten
<&menu> ...
<&terminal> Vælg medarbejder
}
}}
" as ListEmployeesView

ProjectMenuController --> "
{{
salt
{+
title <color:Red>TILFØJ MEDARBEJDER TIL PROJEKT
header AssignEmployeeToProjectView
<&terminal> Indtast medarbejder initialer
}
}}
" as AssignEmployeeToProjectView

ProjectMenuController --> "
{{
salt
{+
title <color:Red>PÅTAG PROJEKTLEDER ROLLE
header AssignProjectLeaderToProjectView
Er du sikker?
<&terminal> Indtast ja/nej
}
}}
" as AssignProjectLeaderToProjectView

ProjectMenuController --> "
{{
salt
{+
title <color:Red>PROJEKT AKTIVITETER
header ListProjectActivitiesView
<&menu> 1. Kravspecifikation
<&menu> 2. Design
<&menu> 3. Half-Life 3
<&menu> ...
<&terminal> Vælg aktivitet:
}
}}
" as ListProjectActivitiesView

ProjectMenuController --> "
{{
salt
{+
title <color:Red>OPRET PROJEKT AKTIVITET
header CreateProjectActivityView
<&terminal> Indtast titel:
}
}}
" as CreateProjectActivityView

ProjectMenuController --> "
{{
salt
{+
title <color:Red>PROJEKT RAPPORT
header ProjectReportView
Projekt nummer:    23001
Projekt leder:     kasy
Medarbejdere:      4
Aktiviteter:       3
Tidsbudget:       300
Registreret tid:       150
Andel:              50.0%
<&terminal> Tryk enter for at vende tilbage:
}
}}
" as ProjectReportView

ListProjectActivitiesView --> "
{{
salt
{+
title <color:Red>PROJECT AKTIVITET MENU
header ProjectActivityMenuController
Aktivitet titel:    Ferie
______________________________
<color:Red><&chevron-right> Se tidsregistreringer
<color:Red><&chevron-right> Opret tidsregistrering
<&chevron-right> tilbage
}
}}
" as ProjectActivityMenuController

ProjectActivityMenuController --> "
{{
salt
{+
title <color:Red>OPRET TIDSREGISTRERING
header CreateWorktimeRegistrationView
<&terminal> Indtast timer:
}
}}
" as CreateWorktimeRegistrationView

ProjectActivityMenuController --> "
{{
salt
{+
title <color:Red>PROJEKT AKTIVITETER
header ListProjectActivitiesView
<&menu> 56. 02/03-2023 : 1.5
<&menu> 99. 02/07-2023 : 4.0
<&menu> 103. 02/10-2023 : 1.0
<&menu> ...
<&terminal> Vælg tidsregistrering:
}
}}
" as ListWorktimeRegistrationsView

ListWorktimeRegistrationsView --> "
{{
salt
{+
title <color:Red>REDIGER TIDSREGISTRERING
header EditWorktimeRegistrationView
<&terminal> Indtast timer:
}
}}
" as EditWorktimeRegistrationView

@enduml
